kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gold
provisioner: kubernetes.io/cinder
parameters:
  type: iscsi
  availability: nova
